# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "HVW Helmut Veith Memorial Workshop 2019"
email: "michael.morak@aau.at "
description: "This is a workshop held annualy in memory of Helmut Veith."
baseurl: "/hvw2019"
url: "https://hvmw.github.io"
permalink: "/blog/:title"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no" # what's that?

# Organizer Info
organizerName: "Anna Prianichnikova, Ana Sokolova, Michael Morak"
organizerAlternateName: "The HVW Organizers"
organizerDescription: "A team of researchers and colleagues of Helmut Veith."
organizerEmail: "pria@forsyte.tuwien.ac.at"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://forsyte.at/people/veith/"

# Head
metaKeywords: "event, conference, workshop, meeting, logic, ai, databases, verification"
#twitterAccount: ""
#socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
#socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "News"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Participants"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Location"}
bottomNavigationLinks:
 - {link: "https://tinyurl.com/hvw2019", text: "Register"}
rightNavigationButtons:
 - {link: "https://tinyurl.com/hvw2019", text: "Register"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Helmut Veith Memorial Workshop"
eventDate: "Turracher Höhe, Austria | March 17 - 20, 2019"
#typeoutTextValues: '"", "Logic", "Verification", "Model Checking", "Skiing"'
#typeoutFallback: ""
heroButtons:
 - {permalink: "/#tickets", text: "Register"}

# About Block
aboutTitle: "About HVW 2019"
aboutBlock:
 - {title: "Workshop", image: "workshop.jpg", text: "A workshop for logicians in computer science, held in memory of Helmut Veith, with an emphasis on the combination of research and social activities. In 2014, Helmut contacted Georg (Moser) with the following idea." }
 - {title: "The Idea", image: "idea.jpg", text: "Folgende Idee (heute am Lift): Vielleicht sollte man eine Tradition eines Logik-in-CS Workshops in Österreich einführen, so nach dem Prinzip am Vormittag arbeiten, am Nachmittag auf der Piste (oder im Bad). Wenn man das zu einem Randtermin macht (März), kann man wahrscheinlich ein gutes Hotel zu einem vernünftigen Preis bekommen, oder es gibt ein Schullandheim etc." }
 - {title: "Research and Social Activities", image: "skiing.jpg", text: "This workshop, now in its third edition, aims to bring this idea to life. It will be held from Monday, March 18, to Wednesday, March 20, 2019, at the Schlosshotel Seewirt, Turracher Höhe, Austria, with arrival on Sunday, March 17, and includes three nights accommodation." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "15", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "12", specialCharacter: "", info: "hours", detail: "of talks"}
 - {count: "42", specialCharacter: "", info: "km", detail: "of slopes for skiing"}

# Latest News Block
latestNewsTitle: "Latest News"

# Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
#rockstarSpeakersCount: 4
#rockstarSpeakersTitle: "Rockstar speakers"
#rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Venue"
eventLocationName: "Schlosshotel Seewirt"
eventLocationLink: "https://www.schlosshotel-seewirt.com/"
eventStreetAddress: "Turracher Höhe 33"
eventAddressLocality: "8864 Turracher Höhe"
eventAddressLocalityRegion: "Styria"
eventPostalCode: "8864"
eventAddressCountry: "Austria"
eventStartTime: "2019-03-18T09:00"
eventDoorTime: "08:30"
eventEndTime: "2019-03-20T12:30"
eventPlaceCoordinates: "46.9245364, 13.8699186"
mapCenterCoordinates: "46.9265729, 13.8661731"
mapMobileCenterCoordinates: "46.9245364, 13.8699186"

# Venue Block
venueBlockTitle: "Location"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Turracher Höhe"
venueFeatures: ["42km of groomed slopes", "14 lifts to take you up the mountain", "Austria's biggest funpark - if you dare"]

# Partners Block
partnersTitle: "Sponsors"

# Tickets Block
ticketsTitle: "Registration"
ticketsInfo: "Registration includes accommodation, coffee brakes, breakfast, and dinner."
ticketsOffers:
 -
  name: "Non-Skiing"
  price: "480"
  priceCurrency: "EUR"
  buyButtonLink: "https://tinyurl.com/yyzop4pw"
  buyButtonText: "Register"
  ticketContentList: ["Three nights at Schlosshotel Seewirt", "Participation in workshop", "No skiing tickets"]
 -
  name: "Full Registration"
  price: "579"
  priceCurrency: "EUR"
  featured: true
  buyButtonLink: "https://tinyurl.com/y46j6a6e"
  buyButtonText: "Register"
  ticketContentList: ["Three nights at Schlosshotel Seewirt", "Participation in workshop", "Afternoon skiing tickets for workshop days"]
 -
  name: "Guest"
  price: "N/A"
  priceCurrency: "EUR"
  featured: true
  buyButtonLink: "https://tinyurl.com/y5dk5gfn"
  buyButtonText: "Register"
  ticketContentList: ["Staying together with full participant", "No workshop participation", "Price and details by individual arrangement"]

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Previous Workshops"
  links:
   - {link: "http://http://hvw2018.cs.uni-salzburg.at/", text: "HVW 2018"}
   - {link: "http://cbr.uibk.ac.at/events/hvw/", text: "HVW 2017"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:pria@forsyte.tuwien.ac.at", text: "Anna Prianichnikova"}
   - {link: "mailto:sokolova.ana@gmail.com", text: "Ana Sokolova"}
   - {link: "mailto:michael.morak@aau.at", text: "Michael Morak"}

# Blog
blogTitle: "Latest News"
blogCommentsEnabled: true
discusShortName: "hvw2019"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Organizational Committee"
aboutUs: "As friends and colleagues of Helmut, we aim to bring his idea of an Austrian workshop for logic in computer science to life. The idea to emphasize a combination of research and social activities was born when Helmut contacted Georg (Moser, organizer of the first edition of the workshop) in 2014: >> Folgende Idee (heute am Lift): Vielleicht sollte man eine Tradition eines Logik-in-CS Workshops in Österreich einführen, so nach dem Prinzip am Vormittag arbeiten, am Nachmittag auf der Piste (oder im Bad).  Wenn man das zu einem Randtermin macht (März), kann man wahrscheinlich ein gutes Hotel zu einem vernünftigen Preis bekommen, oder es gibt ein Schullandheim etc. <<"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "46.9245364, 13.8699186"
logisticsMapMobileCenterCoordinates: "46.9245364, 13.8699186"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Turracher Höhe"
directionDetailsCards:
 - {title: "From the Airport", information: 'The nearest airport is in Klagenfurt. We can arrange taxi services from the airport for you. Please contact us if you need this.'}
 - {title: "Public Transport", information: 'Train services run from Vienna to Unzmarkt. From there, we will organize a shuttle service. Details will be published here.'}
